language: cpp
sudo: false


  
env:
  global:
  - CXX=g++-6
  - CC=gcc-6
  - CUDACXX=/usr/local/cuda-9.2/bin/nvcc
  - LD_LIBRARY_PATH=/usr/local/nvidia/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/nvvm/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64/stubs${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/targets/x86_64-linux/lib/stubs/:+:${LD_LIBRARY_PATH}}
  - PATH=/usr/local/cuda-9.2/bin${PATH:+:${PATH}}
  - CGO_LDFLAGS="${CGO_LDFLAGS} -L /usr/local/cuda-9.2/lib64/stubs"
  
addons: &addons
  - glide
  - cmake
  - libnccl2
  - cuda-cudart-dev-9-2
  - cuda-libraries-9-2
  - cuda-libraries-dev-9-2
  - cuda-cublas-dev-9-2
  - cuda-misc-headers-9-2
  - cuda-nvml-dev-9-2
  - libcudnn7
  - libcudnn7-dev
  - build-essential
  - git
  - wget
  - libatlas-base-dev
  - libboost-all-dev
  - libgflags-dev
  - libgoogle-glog-dev
  - libhdf5-serial-dev
  - libleveldb-dev
  - liblmdb-dev
  - libopencv-dev
  - libprotobuf-dev
  - libsnappy-dev
  - protobuf-compiler
  - python-dev
  - python-numpy
  - python-pip
  - python-setuptools
matrix:
  allow_failures:
    - os: osx
  include:
    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc6
      addons: &gcc6
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:masterminds/glide
            - sourceline: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
                /
              key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
            - sourceline: deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64
                /
          packages:
            - g++-6
            - *addons
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      compiler: clang
      addons: &clang39
        apt:
          sources:
            - llvm-toolchain-precise-3.9
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:masterminds/glide
            - sourceline: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
                /
              key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
            - sourceline: deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64
                /
          packages:
            - clang-3.9
            - *addons
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.10.x bash)"
  - go env
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/rai-project/go-caffe
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/rai-project/go-caffe/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/rai-project/go-caffe
  - cd $HOME/gopath/src/github.com/rai-project/go-caffe
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew tap homebrew/science && brew update && brew install boost snappy leveldb protobuf gflags glog szip lmdb hdf5 homebrew/science/opencv ; fi; echo "done brewing..."
  - cd ${HOME}
  - git clone --depth 1 https://github.com/BVLC/caffe.git ${HOME}/caffe
  - mkdir ${HOME}/caffe_build && cd ${HOME}/caffe_build
  - cmake -DCPU_ONLY=ON -DBUILD_python=OFF -DBUILD_docs=OFF ${HOME}/caffe
  - make
  - make install
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mv install /opt/caffe
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      cp -r install/* /usr/local/
    fi
  - go get github.com/Masterminds/glide
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - cd ${TRAVIS_BUILD_DIR}
  - dep ensure
  - rm -fr vendor/github.com/Sirupsen
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - sudo find / -name cublas_v2.h
  - go build

script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)

