language: cpp
sudo: false


cache:
  directories:
  - $HOME/caffe

addons: &addons
  - build-essential
  - git
  - wget
  - libatlas-base-dev
  - libboost-all-dev
  - libgflags-dev
  - libgoogle-glog-dev
  - libhdf5-serial-dev
  - libleveldb-dev
  - liblmdb-dev
  - libopencv-dev
  - libprotobuf-dev
  - libsnappy-dev
  - protobuf-compiler
  - python-dev
  - python-numpy
  - python-pip
  - python-setuptools
matrix:
  include:
    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc6
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - *addons
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      compiler: clang
      addons: &clang39
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - *addons
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | bash)"
  - go env
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/rai-project/go-caffe
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/rai-project/go-caffe/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/rai-project/go-caffe
  - cd $HOME/gopath/src/github.com/rai-project/go-caffe
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install boost snappy leveldb protobuf gflags glog szip lmdb; fi
  - cd ${HOME}
  - git clone --depth 1 https://github.com/BVLC/caffe.git ${HOME}/caffe
  - pip install --upgrade pip
  - mkdir ${HOME}/caffe_build && cd ${HOME}/caffe_build
  - cmake -DCPU_ONLY=ON -DBUILD_python=OFF -DBUILD_docs=OFF ${HOME}/caffe
  - make
  - make install
  - mv install /opt/caffe
  - ls -l /opt/caffe
  - go get github.com/Masterminds/glide


install:
  - cd ${TRAVIS_BUILD_DIR}
  - glide install --force
  - rm -fr vendor/github.com/Sirupsen
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - go build

script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)

